### ISSUE TITLE
I got an error following the tutorial of Lottie

### ISSUE THREAD

**Issue by DiomedesDominguez** [CrossGeeks/Xamarin.Samples#9]
I got the following error message:
Didn't find class "com.airbnb.lottie.R$styleable" on path: DexPathList[[zip file "/data/app/com.dnmoft.coopnama-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dnmoft.coopnama-1/lib/arm, /vendor/lib, /system/lib]]

![captura de pantalla 2018-01-26 a la s 12 11 37](https://user-images.githubusercontent.com/4379316/35449150-8efe265a-0292-11e8-8e84-789620bddfd6.png)
![captura de pantalla 2018-01-26 a la s 12 15 45](https://user-images.githubusercontent.com/4379316/35449176-accb9780-0292-11e8-931d-87c82fecad2a.png)
![captura de pantalla 2018-01-26 a la s 12 12 13](https://user-images.githubusercontent.com/4379316/35449153-929badf0-0292-11e8-9b48-3b13d74381c4.png)

I changed the content of the file with the one from many other tutorials and it keeps showing the same message.

Also also, It only appears when set the control in the XAML.

**Comment by DiomedesDominguez** [comment]
I found the solution: I must select the latest version of the SDK, in this case Android 8.0
![captura de pantalla 2018-01-30 a la s 15 45 16](https://user-images.githubusercontent.com/4379316/35587623-b6b1f86c-05d4-11e8-8dc7-dd53bb176076.png)

**Comment by nosweat** [comment]
I chose a latest version Oreo 8.1 api 27 and this error occurs to me
